version: "3.5"
services:
  nginx-api:
    env_file: .env
    container_name: status-nginx-api-${generation_timestamp}
    build:
      dockerfile: docker/nginx-api
      context: .
    volumes:
    - ./api:/var/www/html
    ports:
    - "0:80"
    links:
    - php
  php:
    env_file: .env
    container_name: status-php-api-${generation_timestamp}
    build:
      dockerfile: docker/php
      context: .
    volumes:
    - ./api:/var/www/html
  frontend:
    env_file: .env
    container_name: status-php-ui-${generation_timestamp}
    build:
      dockerfile: docker/frontend
      context: .
    volumes:
    - ./ui:/var/www/html
    ports:
    - "0:9000"
  mysql:
    env_file: .env
    container_name: status-mysql-${generation_timestamp}
    image: mysql:latest
    ports:
    - "0:3306"
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
